# Generated by Django 4.1.3 on 2023-01-19 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator])),
                ('title', models.CharField(max_length=70)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
